spring.application.name=cashcards

spring.datasource.url=jdbc:h2:mem:cashcarddb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

spring.jpa.hibernate.ddl-auto=none

cashcard.users.sarah.username=${CASHCARD_USERS_SARAH_USERNAME}
cashcard.users.sarah.password=${CASHCARD_USERS_SARAH_PASSWORD}

cashcard.users.hank.username=${CASHCARD_USERS_HANK_USERNAME}
cashcard.users.hank.password=${CASHCARD_USERS_HANK_PASSWORD}

cashcard.users.kumar.username=${CASHCARD_USERS_KUMAR_USERNAME}
cashcard.users.kumar.password=${CASHCARD_USERS_KUMAR_PASSWORD}